// Generated by CoffeeScript 1.6.3
jQuery.sap.declare("sap.ui.demo.myFiori.Component");

sap.ui.core.UIComponent.extend("sap.ui.demo.myFiori.Component", {
  createContent: function() {
    var deviceModel, i18nModel, oModel, oView;
    oView = sap.ui.view({
      id: "app",
      viewName: "sap.ui.demo.myFiori.view.App",
      type: "JS",
      viewData: {
        component: this
      }
    });
    oModel = new sap.ui.model.json.JSONModel("model/mock.json");
    oView.setModel(oModel);
    i18nModel = new sap.ui.model.resource.ResourceModel({
      bundleUrl: "i18n/messageBundle.properties"
    });
    oView.setModel(i18nModel, "i18n");
    deviceModel = new sap.ui.model.json.JSONModel({
      isPhone: jQuery.device.is.phone,
      listMode: (jQuery.device.is.phone ? "None" : "SingleSelectMaster"),
      listItemType: (jQuery.device.is.phone ? "Active" : "Inactive")
    });
    deviceModel.setDefaultBindingMode("OneWay");
    oView.setModel(deviceModel, "device");
    return oView;
  }
});
