// Generated by CoffeeScript 1.6.3
jQuery.sap.declare("sap.ui.demo.myFiori.util.Formatter");

jQuery.sap.require("sap.ui.core.format.DateFormat");

sap.ui.demo.myFiori.util.Formatter = {
  _statusStateMap: {
    Neu: "Warning",
    Initial: "Success"
  },
  statusState: function(value) {
    var map;
    map = sap.ui.demo.myFiori.util.Formatter._statusStateMap;
    if (value && map[value]) {
      return map[value];
    } else {
      return "None";
    }
  },
  date: function(value) {
    var oDateFormat;
    if (value) {
      oDateFormat = sap.ui.core.format.DateFormat.getDateTimeInstance({
        pattern: "yyyy-MM-dd"
      });
      return oDateFormat.format(new Date(value));
    } else {
      return value;
    }
  },
  quantity: function(value) {
    var err;
    try {
      return (value ? parseFloat(value).toFixed(0) : value);
    } catch (_error) {
      err = _error;
      return "Not-A-Number";
    }
  }
};
