// Generated by CoffeeScript 1.6.3
jQuery.sap.declare("sap.ui.demo.myFiori.util.Grouper");

sap.ui.demo.myFiori.util.Grouper = {
  BillingStatus: function(oContext) {
    var status;
    status = oContext.getProperty("BillingStatus");
    return {
      key: status,
      text: status
    };
  },
  GrossAmount: function(oContext) {
    var currency, key, price, text;
    price = oContext.getProperty("GrossAmount");
    currency = oContext.getProperty("CurrencyCode");
    key = void 0;
    text = void 0;
    if (price <= 5000) {
      key = "LE10";
      text = "< 5000 " + currency;
    } else if (price <= 10000) {
      key = "LE100";
      text = "< 10.000  " + currency;
    } else {
      key = "GT100";
      text = "> 10.000 " + currency;
    }
    return {
      key: key,
      text: text
    };
  }
};
