// Generated by CoffeeScript 1.6.3
sap.ui.jsview("sap.ui.demo.myFiori.view.App", {
  getControllerName: function() {
    return "sap.ui.demo.myFiori.view.App";
  },
  createContent: function(oController) {
    var empty, master;
    this.setDisplayBlock(true);
    this.app = new sap.m.SplitApp();
    master = sap.ui.jsview("Master", "sap.ui.demo.myFiori.view.Master");
    master.getController().nav = this.getController();
    this.app.addPage(master, true);
    empty = sap.ui.xmlview("Empty", "sap.ui.demo.myFiori.view.Empty");
    this.app.addPage(empty, false);
    return new sap.m.Shell("Shell", {
      title: "{i18n>ShellTitle}",
      showLogout: false,
      app: this.app
    });
  }
});
